# Generated by Django 4.0.5 on 2022-06-04 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='rasmlar/')),
                ('total_expanditure', models.IntegerField(default=0)),
                ('total_income', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=100)),
                ('president', models.CharField(blank=True, max_length=100)),
                ('coach', models.CharField(blank=True, max_length=100)),
                ('stadium', models.CharField(blank=True, max_length=100)),
                ('foundation', models.DateField(blank=True, null=True)),
                ('record_arrival', models.CharField(max_length=300)),
                ('record_departure', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.club')),
            ],
        ),
        migrations.CreateModel(
            name='U_20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.IntegerField()),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.club')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('value_by_tft', models.IntegerField()),
                ('date', models.DateField()),
                ('new_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.club')),
                ('old_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='former_players', to='asosiy.club')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.player')),
            ],
        ),
    ]
