# Generated by Django 4.0.5 on 2022-06-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='rasmlar/'),
        ),
    ]
