# Generated by Django 4.0.5 on 2022-06-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_club_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u_20',
            name='date',
        ),
        migrations.AddField(
            model_name='u_20',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
