# Generated by Django 4.0.5 on 2022-06-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_remove_u_20_date_u_20_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u_20',
            name='age',
            field=models.IntegerField(),
        ),
    ]
