# Generated by Django 4.0.5 on 2022-06-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_alter_u_20_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='new_club',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='old_club',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
