# Generated by Django 4.0.5 on 2022-06-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_alter_transfer_new_club_alter_transfer_old_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
