# Generated by Django 4.0.5 on 2022-06-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0007_player_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=30)),
                ('expenditure', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Income_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=30)),
                ('income', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='total_expanditure',
        ),
        migrations.RemoveField(
            model_name='club',
            name='total_income',
        ),
    ]
