# Generated by Django 4.0.5 on 2022-06-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0010_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='date',
        ),
        migrations.AddField(
            model_name='transfer',
            name='season',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
