# Generated by Django 4.0.5 on 2022-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0011_remove_transfer_date_transfer_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u_20',
            name='age',
        ),
        migrations.AddField(
            model_name='u_20',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
