# Generated by Django 4.0.5 on 2023-02-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0012_remove_u_20_age_u_20_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HozirgiMavsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavsum', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='club',
            name='president',
        ),
        migrations.RemoveField(
            model_name='club',
            name='record_arrival',
        ),
        migrations.RemoveField(
            model_name='club',
            name='record_departure',
        ),
        migrations.RemoveField(
            model_name='club',
            name='stadium',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='value_by_tft',
        ),
        migrations.AddField(
            model_name='club',
            name='eng_katta_sotuv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='eng_katta_tr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='murabbiy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='prezident',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='tax_narx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.club'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='new_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.club'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='old_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sotganlari', to='asosiy.club'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.player'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='season',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='value',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='U_20',
        ),
    ]
